<?xml version="1.0" encoding="UTF-8"?>
<databrowser>
  <title></title>
  <show_toolbar>true</show_toolbar>
  <update_period>3.0</update_period>
  <scroll_step>5</scroll_step>
  <scroll>false</scroll>
  <start>2024-03-16 12:10:24.560</start>
  <end>2024-03-16 12:22:41.560</end>
  <archive_rescale>STAGGER</archive_rescale>
  <foreground>
    <red>0</red>
    <green>0</green>
    <blue>0</blue>
  </foreground>
  <background>
    <red>255</red>
    <green>255</green>
    <blue>255</blue>
  </background>
  <title_font>Liberation Sans|20|1</title_font>
  <label_font>Liberation Sans|14|1</label_font>
  <scale_font>Liberation Sans|12|0</scale_font>
  <legend_font>Liberation Sans|14|0</legend_font>
  <axes>
    <axis>
      <visible>true</visible>
      <name>Value 1</name>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>-159.0</min>
      <max>95.0</max>
      <grid>true</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
  </axes>
  <annotations>
  </annotations>
  <pvlist>
    <pv>
      <display_name>1</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch01:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>2</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch02:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>127</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>3</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch02:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>0</red>
        <green>255</green>
        <blue>127</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>4</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch04:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>127</red>
        <green>0</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>5</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch05:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>255</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>6</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch06:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>0</red>
        <green>255</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>7</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch07:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>0</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>8</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch08:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>127</red>
        <green>255</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>9</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch09:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>0</red>
        <green>127</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>10</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch10:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>0</green>
        <blue>127</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>11</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch11:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>0</red>
        <green>127</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>12</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch12:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>127</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
    <pv>
      <display_name>13</display_name>
      <visible>true</visible>
      <name>FDAS:01:SA:Ch13:Mean-I</name>
      <axis>0</axis>
      <color>
        <red>127</red>
        <green>63</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
    </pv>
  </pvlist>
</databrowser>
